# Univariate Feature Imputation

In [8]:
import numpy as np
import pandas as pd
X=np.array([[np.nan,2],[6,np.nan],[7,6]])
X

array([[nan,  2.],
       [ 6., nan],
       [ 7.,  6.]])

In [4]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy="mean")
imp.fit_transform(X)


array([[6.5, 2. ],
       [6. , 4. ],
       [7. , 6. ]])

In [6]:
13/2

6.5

In [9]:
# for categorical features:

df=pd.DataFrame([["a","x"],[np.nan,"y"],["a",np.nan],["b","y"]],dtype="category")

In [10]:
df

0    1
0    a    x
1  NaN    y
2    a  NaN
3    b    y

In [12]:
imp_1=SimpleImputer(strategy="most_frequent")
print(imp_1.fit_transform(df))

[['a' 'x']
 ['a' 'y']
 ['a' 'y']
 ['b' 'y']]


# Multivariate feature imputation:

In [14]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

imp_iter=IterativeImputer(max_iter=10,random_state=10)
imp_iter.fit_transform(X)

array([[5.000012, 2.      ],
       [6.      , 3.999988],
       [7.      , 6.      ]])

# nearest neighbour Imputer

In [16]:
Y=np.array([[1,2,np.nan],[3,4,3],[np.nan,6,5],[8,8,7]])
Y

array([[ 1.,  2., nan],
       [ 3.,  4.,  3.],
       [nan,  6.,  5.],
       [ 8.,  8.,  7.]])

In [17]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2,weights="uniform")
imputer.fit_transform(Y)

array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])